name: ci 
on:
  push:
    branches:
      - develop
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name: Install Poetry
        run: |
          pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: poetry
      - name: Set Poetry environment
        run: |
          poetry env use 3.8
      - name: Install dependencies
        run: |
          poetry install --no-root
      - name: Deployment setup
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com 
      - name: Deploy document
        run: |
          RELEASE_VERSION=$(poetry run toml get --toml-path pyproject.toml tool.poetry.version)
          poetry run mike deploy --push --update-aliases ${RELEASE_VERSION} latest